<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dashboard</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])

</head>
<body class="bg-[#c6ffc6] ">
    <div class="p-8 rounded-lg">
        <div class="flex w-full flex-col items-center">
            <div class="flex items-center">
                <img src="{{ auth()->user()->avatar ? url('storage/' . auth()->user()->avatar) : 'https://ui-avatars.com/api/?name=' . auth()->user()->name }}" alt="{{ auth()->user()->name }}" class="w-20 h-20 rounded-full border-2">
            </div>
            <div>
                <h2 class="text-xl font-bold">{{ auth()->user()->name }}</h2>
            </div>
        </div>
        <div class="mt-4 flex justify-center text-center">
            <p class="text-lg font-light">{{ auth()->user()->bio }}</p>
        </div>
        <div class="mt-4 ]">
            {{-- <p class="text-lg font-bold">Links</p> --}}
            <div class="flex flex-col w-full gap-5">
                <button class="flex items-center bg-green-300 p-4 w-full shadow-[5px_5px_0px_0px_rgba(0,0,0,255)] hover:translate-y-[5px] hover:translate-x-[5px] hover:shadow-none transition-all border-2 rounded-full  ">
                    <img src="{{ asset('images/instagram.png') }}" class="w-[3rem] " alt="">
                    <a href="{{ auth()->user()->instagram }}" class="font-bold text-2xl justify-center flex w-full">Instagram</a>
                </button>
                <button class="flex items-center bg-green-300 p-4 w-full shadow-[5px_5px_0px_0px_rgba(0,0,0,255)] hover:translate-y-[5px] hover:translate-x-[5px] hover:shadow-none transition-all border-2 rounded-full  ">
                    <img src="{{ asset('images/website.png') }}" class="w-[3rem]" alt="">
                    <a href="{{ auth()->user()->website }}" class="font-bold text-2xl justify-center flex w-full">Website</a>
                </button>
                <button class="flex items-center bg-green-300 p-4 w-full shadow-[5px_5px_0px_0px_rgba(0,0,0,255)] hover:translate-y-[5px] hover:translate-x-[5px] hover:shadow-none transition-all border-2 rounded-full  ">
                    <img src="{{ asset('images/linkedin.png') }}" class="w-[3rem]" alt="">
                    <a href="{{ auth()->user()->linkedin }}" class="font-bold text-2xl justify-center flex w-full">LinkedIn</a>
                </button>
                <button class="flex items-center bg-green-300 p-4 w-full shadow-[5px_5px_0px_0px_rgba(0,0,0,255)] hover:translate-y-[5px] hover:translate-x-[5px] hover:shadow-none transition-all border-2 rounded-full  ">
                    <img src="{{ asset('images/github.png') }}" class="w-[3rem]" alt="">
                    <a href="{{ auth()->user()->github }}" class="font-bold text-2xl justify-center flex w-full">Github</a>
                </button>
            </div>
        </div>
        {{-- <button class="flex items-center bg-green-400 p-4 w-full shadow-[5px_5px_0px_0px_rgba(0,0,0,255)] hover:translate-y-[5px] hover:translate-x-[5px] hover:shadow-none transition-all border-2 mt-5 rounded-full  ">
            <a href="/profile/edit" class="font-bold text-2xl justify-center flex w-full">Edit Profile</a>
        </button> --}}
    </div>
    <footer class="absolute bottom-5 w-full flex justify-center">
        <h1 class="font-bold">Generated By SynchronizeTeams</h1>
    </footer>
</body>
</html>


